CREATE EXTENSION pgcrypto;

CREATE TABLE users (
id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY NOT NULL,
email TEXT NOT NULL UNIQUE,
chat_id TEXT NOT NULL,
role TEXT NOT NULL,
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE sessions (
id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY NOT NULL,
user_id UUID REFERENCES users(id),
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE codes (
id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY NOT NULL,
code TEXT,
attempts INT,
user_id UUID REFERENCES users(id),
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);

INSERT INTO users (id, email, chat_id, role, created_at, updated_at)
VALUES (DEFAULT, 'e.green@berizaryad.ru', '392476956', 'admin', DEFAULT, DEFAULT);
