openapi: 3.0.0
info:
  title: "Swagger BeriZaryad"
  description: "Коллекция API Бери Заряд!"
  version: "1.0.0"

servers:
  - url: https://preprodapi.berizaryad.ru
    description: Препрод API
  - url: https://devapi.berizaryad.ru
    description: Тестовый API
  - url: https://stageapi.berizaryad.ru
    description: Стейдж API

tags:
- name: "auth"
  description: "Авторизация пользователей"
- name: "locations"
  description: "Информация о локациях автоматов"
- name: "cards"
  description: "Информация о картах пользователей"
- name: "users"
  description: "Информация о пользователях"
- name: "vendings"
  description: "Информация о локациях автоматов"

paths:
  /auth:
    post:
      tags:
      - "auth"
      summary: "Регистрация нового пользователя"
      description: "Метод для регистрации нового пользователя. Вызывается только для пользователей с пустым статусом (старые юзеры без подтвержденных номеров телефонов с необходимостью в скорейшем времени добавить его) или статусом approved. <br><br>При отправке только номера телефона, если в системе найден такой пользователь (в статусе ожидания активации), на указанный телефон придет код подтверждения."
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/post_auth'
      responses:
       "200":
          description: "Успешная авторизация"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post_auth200'  
       "400":
          description: "Неверный номер телефона"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post_auth400'
       "500":
          description: "Ошибка на стороне сервера"

  /locations:
    get:
      tags:
      - "locations"
      summary: "Список локаций автоматов"
      description: "Возвращает все существующие автоматы и их адреса"
      responses:
       "200":
          description: "Успешный запрос"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/locations'  
       "500":
          description: "Ошибка на стороне сервера"

  /locations/{id}:
    get:
      tags:
      - "locations"
      summary: "Информация по конкретной локации"
      description: "Возвращает информацию об одной точке"
      parameters:
        - name: id
          in: path
          required: true
          description: ID искомого аппарата.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
       "200":
          description: "Успешный запрос"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/locationsId'
       "500":
          description: "Ошибка на стороне сервера"

  /blocked_cards:
    get:
      tags:
      - "cards"
      summary: "Список заблокированных карт"
      description: "Возвращает все забокированные для использования в приложении карты"
      responses:
       "200":
          description: "Успешный запрос"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/blockedCards'  
       "500":
          description: "Ошибка на стороне сервера"

  /users:
    get:
      tags:
      - "users"
      summary: "Данные текущего пользователя"
      description: "Возвращает информацию о текущем пользователе. Доступен только из сессии"
      security:
        - cookieAuth: []
      responses:
       "200":
          description: "Успешный запрос"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'  
       "401":
          description: "Неавторизованный запрос"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users401'
       "500":
          description: "Ошибка на стороне сервера"





components:
  securitySchemes:
    cookieAuth:         # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: JSESSIONID  # cookie name

  schemas:
    locations:
      type: object
      properties:
        data:
          type: object
          example: [{"id":"1485","type":"vendings","attributes":{"id":1485,"status":"not_responding","address":"Москва, Щёлковское шоссе, 100с3","latitude":55.812763,"longitude":37.834515,"description":"Автофлайт","working-time":{"open-at":"09:00","close-at":"20:00","tomorrow-open-at":"09:00","current-day":3},"num-cells-total":8,"num-empty-cells":6,"num-usb-type-c-chargers":1,"num-lightning-chargers":1,"num-micro-usb-chargers":1,"num-charged-chargers":1,"plan":null,"zone":"RUS","plans":[],"required-deposit-amount":null,"machine-type":"LDX","pin-color":"#0092FB"}},{"id":"3344","type":"vendings","attributes":{"id":3344,"status":"not_responding","address":"Восточная улица, 4к1с10","latitude":55.714262,"longitude":37.655176,"description":"офис восточная","working-time":{"open-at":"00:00","close-at":"23:59","tomorrow-open-at":"00:00","current-day":3},"num-cells-total":8,"num-empty-cells":7,"num-usb-type-c-chargers":1,"num-lightning-chargers":1,"num-micro-usb-chargers":1,"num-charged-chargers":1,"plan":null,"zone":"RUS","plans":[],"required-deposit-amount":null,"machine-type":"ReLink","pin-color":"#8247E5"}}]

    locationsId:
      type: object
      properties:
        data:
          type: object
          example: {"data":{"id":"1485","type":"vendings","attributes":{"status":"not_responding","address":"пос. Ржавки, 2-й микрорайон, стр.20","latitude":55.999445,"longitude":37.259997,"description":"Эzо Грузинская Кухня","working-time":{"open-at":"10:00","close-at":"22:00","tomorrow-open-at":"10:00","current-day":4},"num-cells-total":8,"num-empty-cells":2,"num-usb-type-c-chargers":6,"num-lightning-chargers":6,"num-micro-usb-chargers":6,"num-charged-chargers":6,"plan":{"id":5,"payments":[{"amount":0,"next":1800,"message":"30 минут бесплатно"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":86400,"message":"100р/сутки"},{"amount":100,"next":"","message":"100р/сутки"}],"title":"30 минут бесплатно, далее 100 рублей сутки","description":"\u003cp\u003e\u003cspan style=\"vertical-align: inherit;\"\u003e\u003cspan style=\"vertical-align: inherit;\"\u003e\u003cspan style=\"vertical-align: inherit;\"\u003e\u003cspan style=\"vertical-align: inherit;\"\u003eПри аренде мы проверим активность карты, выполнив операции удержания / удержания на сумму 101 рубль. \u003c/span\u003e\u003c/span\u003e\u003c/span\u003e\u003cspan style=\"vertical-align: inherit;\"\u003e\u003cspan style=\"vertical-align: inherit;\"\u003e\u003cspan style=\"vertical-align: inherit;\"\u003eЭта сумма не будет списана.\u0026nbsp;\u003c/span\u003e\u003c/span\u003e\u003c/span\u003e\u003c/span\u003e\u003cbr /\u003e\u003cspan style=\"vertical-align: inherit;\"\u003e\u003cspan style=\"vertical-align: inherit;\"\u003e\u003cspan style=\"vertical-align: inherit;\"\u003e\u003cspan style=\"vertical-align: inherit;\"\u003eПосле начала 30 минут - бесплатны, после чего будет списано 100 рублей и с этого момента будет списываться 100 рублей за каждые 24 часа аренды.\u003c/span\u003e\u003c/span\u003e\u003c/span\u003e\u003c/span\u003e\u003c/p\u003e"},"zone":"RUS","plans":[],"required-deposit-amount":null,"machine-type":"LDX","pin-color":"#0092FB"}}}

    blockedCards:
      type: object
      properties:
        startsWith:
          type: string
          example: "480110"
        endsWith:
          type: string
          example: "2957"
        expDate:
          type: string
          example: "12/23"

    users:
      type: object
      properties:
        name:
          type: string
          example: "name"

    users401:
      type: object
      properties:
        error:
          type: string
          example: "Вам необходимо войти в систему или зарегистрироваться."

    post_auth:
      type: object
      required:
      - phone
      - email
      - password
      properties:
        phone:
          type: string
          example: '79181444314'
        email:
          type: string
          example: 'email@mail.com'
        password:
          type: string
          example: '***'
    
    post_auth200:
      type: object
      properties:
        status:
          type: string
          example: 'success'
        data:
          type: object
          example: {
                    "id": 5379,
                    "type": "users",
                    "attributes": {
                        "phone": "79181444314",
                        "status": "not_approved",
                        "email": null,
                        "bonus-time-sec": null,
                        "bonus-score": 0,
                        "zone": null,
                        "sms-attempts": {
                            "count": 2,
                            "send-time": "2022-07-11T15:32:18+03:00",
                            "pin-expiry": 60,
                            "next-event-wait": 60,
                            "message-id": "1523576974538791327"
                        },
                        "charger-type": "universal",
                        "promotional-code": "beri5379",
                        "taken-orders-count": 0,
                        "card-authorization-amount": "101",
                        "card-authorization-currency": "RUB",
                        "are-bonuses-available": true
                    }
                   }
        token: 
          type: string
          example: 'null'

    post_auth400:
      type: object
      properties:
        error:
          type: string
          example: 'Передан неверный номер телефона'
        code:
          type: integer
          example: 1006
        status:
          type: string
          example: 'error'
        backtrace:
          type: object
          example: [
    "/var/www/api/app/controllers/users/registrations_controller.rb:16:in `create'",
    "/home/ruby/.rvm/gems/ruby-2.7.4/gems/actionpack-6.0.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'",
    "/home/ruby/.rvm/gems/ruby-2.7.4/gems/actionpack-6.0.5/lib/abstract_controller/base.rb:195:in `process_action'",
    "/home/ruby/.rvm/gems/ruby-2.7.4/gems/actionpack-6.0.5/lib/action_controller/metal/rendering.rb:30:in `process_action'"
  ]
