openapi: 3.0.0
info:
  title: "Swagger Green-Auth"
  description: "API Sample for Green-Auth service"
  version: "1.0.0"

servers:
  - url: https://password.berizaryad.ru
    description: TEST

paths:
  /checkLogin:
    post:
      summary: "Login check"
      description: "Method for checking if Login is correct"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/post_check_login'
      responses:
       "200":
          description: "Access allowed"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post_check_login200'  
       "400":
          description: "Access is not allowed"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post_check_login400'
       "500":
          description: "Server error"

components:
    post_check_login:
      type: object
      required:
      - login
      properties:
        login:
          type: string
          example: "test@ktrn.com"
    
    post_check_login200:
      type: object
      properties:
        response:
          type: string
          example: "Login accepted"
        status:
          type: integer
          example: 200

    post_check_login400:
      type: object
      properties:
        response:
          type: string
          example: "Login not found in allowed"
        status:
          type: integer
          example: 400
